version: '3'

services:
  web:
    image: ubuntu_nginx:latest
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - /Users/chenguorong/Project/xiaoyinka/xiaoyinka:/data/www/xiaoyinka
      - /Users/chenguorong/Project/xiaoyinka/api:/data/www/api
      - /Users/chenguorong/Project/xiaoyinka/logs/:/data/logs/
  php:
    image: ubuntu_php:latest
    ports:
      - "9000:9000"
    volumes:
      - /Users/chenguorong/Project/xiaoyinka/xiaoyinka:/data/www/xiaoyinka
      - /Users/chenguorong/Project/xiaoyinka/api:/data/www/api
      - /Users/chenguorong/Project/xiaoyinka/logs/:/data/logs/
    links:
      - web

